/*

+─────────┌───────────┌────────┌─────────+
|ASSET_ID |USER_CR_ID |COMP_ID |LAST_UPD |
+─────────└───────────└────────└─────────+

ASSET_ID       INT      NOT NULL    AUTO_INCREMENT                          PRIMARY KEY,
USER_CR_ID     INT      NOT NULL    FOREIGN KEY REFERENCES USERS(USER_ID),
COMP_ID        INT      NOT NULL    FOREIGN KEY REFERENCES COMPANY(COMP_ID),
LAST_UPD       DATETIME DEFAULT     CURRENT_TIMESTAMP                       ON UPDATE CURRENT_TIMESTAMP

*/

CREATE TABLE ASSET_MGMT (
    ASSET_ID       INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_CR_ID     INT      NOT NULL,
    COMP_ID        INT      NOT NULL,
    LAST_UPD       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_CR_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (COMP_ID) REFERENCES COMPANY(COMP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;