/*

+────────┌────────+
|CONV_ID |USER_ID |
+────────└────────+

CONV_ID     INT     NOT NULL    FOREIGN KEY REFERENCES CONVERSATION(CONV_ID),
USER_ID     INT     NOT NULL    FOREIGN KEY REFERENCES USERS(USER_ID),

*/

CREATE TABLE CONVERSATION_PARTICIPANTS (
    CONV_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (CONV_ID, USER_ID),
    FOREIGN KEY (CONV_ID) REFERENCES CONVERSATION(CONV_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
